[2023-03-01 12:52:40,406] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: with_python_operator.get_name 2022-11-18T09:05:00+00:00 [queued]>
[2023-03-01 12:52:40,523] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: with_python_operator.get_name 2022-11-18T09:05:00+00:00 [queued]>
[2023-03-01 12:52:40,524] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-03-01 12:52:40,526] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2023-03-01 12:52:40,527] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-03-01 12:52:40,627] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): get_name> on 2022-11-18T09:05:00+00:00
[2023-03-01 12:52:40,639] {standard_task_runner.py:52} INFO - Started process 14593 to run task
[2023-03-01 12:52:40,667] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'with_python_operator', 'get_name', '2022-11-18T09:05:00+00:00', '--job-id', '3441', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/02_python_operator.py', '--cfg-path', '/tmp/tmp2y64qkvz', '--error-file', '/tmp/tmpp5jqtzfm']
[2023-03-01 12:52:40,680] {standard_task_runner.py:77} INFO - Job 3441: Subtask get_name
[2023-03-01 12:52:41,174] {logging_mixin.py:104} INFO - Running <TaskInstance: with_python_operator.get_name 2022-11-18T09:05:00+00:00 [running]> on host abe4c4997ef7
[2023-03-01 12:52:41,541] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dataheroes
AIRFLOW_CTX_DAG_ID=with_python_operator
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T09:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-18T09:05:00+00:00
[2023-03-01 12:52:41,656] {python.py:118} INFO - Done. Returned value was: None
[2023-03-01 12:52:41,728] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=with_python_operator, task_id=get_name, execution_date=20221118T090500, start_date=20230301T125240, end_date=20230301T125241
[2023-03-01 12:52:42,037] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-01 12:52:42,121] {local_task_job.py:146} INFO - Task exited with return code 0
