[2023-03-01 13:01:52,255] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: with_python_operator.get_name 2022-11-28T22:05:00+00:00 [queued]>
[2023-03-01 13:01:52,391] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: with_python_operator.get_name 2022-11-28T22:05:00+00:00 [queued]>
[2023-03-01 13:01:52,394] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-03-01 13:01:52,401] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2023-03-01 13:01:52,408] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-03-01 13:01:52,498] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): get_name> on 2022-11-28T22:05:00+00:00
[2023-03-01 13:01:52,509] {standard_task_runner.py:52} INFO - Started process 17648 to run task
[2023-03-01 13:01:52,545] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'with_python_operator', 'get_name', '2022-11-28T22:05:00+00:00', '--job-id', '4204', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/02_python_operator.py', '--cfg-path', '/tmp/tmpwtvz5ib3', '--error-file', '/tmp/tmpy4nikvf7']
[2023-03-01 13:01:52,548] {standard_task_runner.py:77} INFO - Job 4204: Subtask get_name
[2023-03-01 13:01:53,038] {logging_mixin.py:104} INFO - Running <TaskInstance: with_python_operator.get_name 2022-11-28T22:05:00+00:00 [running]> on host abe4c4997ef7
[2023-03-01 13:01:53,425] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dataheroes
AIRFLOW_CTX_DAG_ID=with_python_operator
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T22:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T22:05:00+00:00
[2023-03-01 13:01:53,572] {python.py:118} INFO - Done. Returned value was: None
[2023-03-01 13:01:53,703] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=with_python_operator, task_id=get_name, execution_date=20221128T220500, start_date=20230301T130152, end_date=20230301T130153
[2023-03-01 13:01:54,163] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-01 13:01:54,282] {local_task_job.py:146} INFO - Task exited with return code 0
