[2023-03-01 13:09:46,955] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: with_python_operator.get_name 2022-12-08T11:05:00+00:00 [queued]>
[2023-03-01 13:09:47,174] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: with_python_operator.get_name 2022-12-08T11:05:00+00:00 [queued]>
[2023-03-01 13:09:47,177] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-03-01 13:09:47,181] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2023-03-01 13:09:47,181] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-03-01 13:09:47,441] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): get_name> on 2022-12-08T11:05:00+00:00
[2023-03-01 13:09:47,560] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'with_python_operator', 'get_name', '2022-12-08T11:05:00+00:00', '--job-id', '4884', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/02_python_operator.py', '--cfg-path', '/tmp/tmpsn3867uv', '--error-file', '/tmp/tmp66u0yc1k']
[2023-03-01 13:09:47,512] {standard_task_runner.py:52} INFO - Started process 20385 to run task
[2023-03-01 13:09:47,571] {standard_task_runner.py:77} INFO - Job 4884: Subtask get_name
[2023-03-01 13:09:48,263] {logging_mixin.py:104} INFO - Running <TaskInstance: with_python_operator.get_name 2022-12-08T11:05:00+00:00 [running]> on host abe4c4997ef7
[2023-03-01 13:09:49,109] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dataheroes
AIRFLOW_CTX_DAG_ID=with_python_operator
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2022-12-08T11:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-08T11:05:00+00:00
[2023-03-01 13:09:49,467] {python.py:118} INFO - Done. Returned value was: None
[2023-03-01 13:09:49,569] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=with_python_operator, task_id=get_name, execution_date=20221208T110500, start_date=20230301T130947, end_date=20230301T130949
[2023-03-01 13:09:50,205] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-01 13:09:50,379] {local_task_job.py:146} INFO - Task exited with return code 0
