[2023-03-01 12:53:46,450] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: with_python_operator.get_name 2022-11-19T15:05:00+00:00 [queued]>
[2023-03-01 12:53:46,638] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: with_python_operator.get_name 2022-11-19T15:05:00+00:00 [queued]>
[2023-03-01 12:53:46,639] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-03-01 12:53:46,640] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2023-03-01 12:53:46,641] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-03-01 12:53:46,855] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): get_name> on 2022-11-19T15:05:00+00:00
[2023-03-01 12:53:46,938] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'with_python_operator', 'get_name', '2022-11-19T15:05:00+00:00', '--job-id', '3530', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/02_python_operator.py', '--cfg-path', '/tmp/tmpfpkq6shs', '--error-file', '/tmp/tmpilfvl5_j']
[2023-03-01 12:53:46,940] {standard_task_runner.py:77} INFO - Job 3530: Subtask get_name
[2023-03-01 12:53:46,886] {standard_task_runner.py:52} INFO - Started process 14951 to run task
[2023-03-01 12:53:47,427] {logging_mixin.py:104} INFO - Running <TaskInstance: with_python_operator.get_name 2022-11-19T15:05:00+00:00 [running]> on host abe4c4997ef7
[2023-03-01 12:53:47,901] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dataheroes
AIRFLOW_CTX_DAG_ID=with_python_operator
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2022-11-19T15:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-19T15:05:00+00:00
[2023-03-01 12:53:48,024] {python.py:118} INFO - Done. Returned value was: None
[2023-03-01 12:53:48,171] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=with_python_operator, task_id=get_name, execution_date=20221119T150500, start_date=20230301T125346, end_date=20230301T125348
[2023-03-01 12:53:48,758] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-01 12:53:48,893] {local_task_job.py:146} INFO - Task exited with return code 0
