[2023-03-01 12:52:46,237] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: with_python_operator.get_name 2022-11-18T12:05:00+00:00 [queued]>
[2023-03-01 12:52:46,559] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: with_python_operator.get_name 2022-11-18T12:05:00+00:00 [queued]>
[2023-03-01 12:52:46,572] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-03-01 12:52:46,574] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2023-03-01 12:52:46,575] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-03-01 12:52:46,687] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): get_name> on 2022-11-18T12:05:00+00:00
[2023-03-01 12:52:46,694] {standard_task_runner.py:52} INFO - Started process 14633 to run task
[2023-03-01 12:52:46,780] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'with_python_operator', 'get_name', '2022-11-18T12:05:00+00:00', '--job-id', '3450', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/02_python_operator.py', '--cfg-path', '/tmp/tmpz1z_ljg_', '--error-file', '/tmp/tmpxopz6z_b']
[2023-03-01 12:52:46,807] {standard_task_runner.py:77} INFO - Job 3450: Subtask get_name
[2023-03-01 12:52:47,704] {logging_mixin.py:104} INFO - Running <TaskInstance: with_python_operator.get_name 2022-11-18T12:05:00+00:00 [running]> on host abe4c4997ef7
[2023-03-01 12:52:48,179] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dataheroes
AIRFLOW_CTX_DAG_ID=with_python_operator
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T12:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-18T12:05:00+00:00
[2023-03-01 12:52:48,397] {python.py:118} INFO - Done. Returned value was: None
[2023-03-01 12:52:48,499] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=with_python_operator, task_id=get_name, execution_date=20221118T120500, start_date=20230301T125246, end_date=20230301T125248
[2023-03-01 12:52:48,919] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-03-01 12:52:49,020] {local_task_job.py:146} INFO - Task exited with return code 0
