[2023-03-01 13:11:44,763] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: with_python_operator.get_name 2022-12-10T18:05:00+00:00 [queued]>
[2023-03-01 13:11:45,228] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: with_python_operator.get_name 2022-12-10T18:05:00+00:00 [queued]>
[2023-03-01 13:11:45,232] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-03-01 13:11:45,233] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2023-03-01 13:11:45,234] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-03-01 13:11:45,534] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): get_name> on 2022-12-10T18:05:00+00:00
[2023-03-01 13:11:45,565] {standard_task_runner.py:52} INFO - Started process 21061 to run task
[2023-03-01 13:11:45,637] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'with_python_operator', 'get_name', '2022-12-10T18:05:00+00:00', '--job-id', '5052', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/02_python_operator.py', '--cfg-path', '/tmp/tmpvf2tzkh8', '--error-file', '/tmp/tmpf8gojv0i']
[2023-03-01 13:11:45,660] {standard_task_runner.py:77} INFO - Job 5052: Subtask get_name
[2023-03-01 13:11:46,154] {logging_mixin.py:104} INFO - Running <TaskInstance: with_python_operator.get_name 2022-12-10T18:05:00+00:00 [running]> on host abe4c4997ef7
[2023-03-01 13:11:46,897] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dataheroes
AIRFLOW_CTX_DAG_ID=with_python_operator
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2022-12-10T18:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-10T18:05:00+00:00
[2023-03-01 13:11:47,127] {python.py:118} INFO - Done. Returned value was: None
[2023-03-01 13:11:47,251] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=with_python_operator, task_id=get_name, execution_date=20221210T180500, start_date=20230301T131144, end_date=20230301T131147
[2023-03-01 13:11:47,605] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-01 13:11:47,689] {local_task_job.py:146} INFO - Task exited with return code 0
